apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-ingress-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-north-1:476768693646:certificate/9415e72a-64d7-406d-9fc0-78b015014bd5
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
    - host: test.dreamtoday.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netflix-app-76667ff556-nj2dn
                port:
                  number: 80
    - host: k8s-default-netflixi-3bf7bceda7-901566779.eu-north-1.elb.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netflix-app-76667ff556-nj2dn
                port:
                  number: 80
