name: Build and Push to Amazon ECR

on:
  push:
    branches:
      - main  # Change this if your production branch is different

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    name: Build and Deploy Docker Image to ECR
    runs-on: ubuntu-latest
    environment: ecr-push  # Must match your GitHub environment name where secrets exist

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/<YOUR_GITHUB_OIDC_ROLE>
          role-session-name: github-actions
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          docker build -t netflix .

      - name: Tag Docker Image for ECR
        run: |
          docker tag netflix:latest 476768693646.dkr.ecr.eu-north-1.amazonaws.com/devops_sec:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 476768693646.dkr.ecr.eu-north-1.amazonaws.com/devops_sec:latest

      - name: Echo Deployment Triggered
        run: echo "Deployment will be automatically picked up by ArgoCD (auto-sync enabled)"
