name: Build and Push to Amazon ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ecr-push  # MUST match your GitHub environment name

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push Docker image
      run: |
        IMAGE_URI=476768693646.dkr.ecr.eu-north-1.amazonaws.com/devops_sec:latest
        docker build -t netflix .
        docker tag netflix:latest $IMAGE_URI
        docker push $IMAGE_URI
