name: Build and Deploy to EKS via ArgoCD

on:
  push:
    branches:
      - main  # ✅ Change if your prod branch differs

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: CI/CD Pipeline: Build Docker Image and Push to ECR
    runs-on: ubuntu-latest
    environment: ecr-push  # ✅ Your GitHub environment with secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t netflix .

      - name: Tag Docker image for ECR
        run: |
          docker tag netflix:latest 476768693646.dkr.ecr.eu-north-1.amazonaws.com/devops_sec:latest

      - name: Push Docker image to ECR
        run: |
          docker push 476768693646.dkr.ecr.eu-north-1.amazonaws.com/devops_sec:latest

      - name: Done
        run: echo "✅ Image built and pushed. ArgoCD will auto-sync."
