name: Build and Deploy to EKS via ArgoCD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ecr-push  # ✅ Must match GitHub environment name where secrets are stored

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push Docker Image to ECR
      run: |
        docker build -t netflix .
        docker tag netflix:latest 476768693646.dkr.ecr.eu-north-1.amazonaws.com/devops_sec:latest
        docker push 476768693646.dkr.ecr.eu-north-1.amazonaws.com/devops_sec:latest

    # Optional: Check kubeconfig if needed in the future
    # - name: Update kubeconfig
    #   run: aws eks --region eu-north-1 update-kubeconfig --name netflix-cluster

    # No webhook needed if ArgoCD is set to auto-sync
