name: Deploy to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ecr-push  # ✅ MUST MATCH your environment name in GitHub

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: eu-north-1

      - name: Build Docker Image
        run: |
          docker build -t netflix .

      - name: Tag Docker Image
        run: |
          docker tag netflix:latest 476768693646.dkr.ecr.eu-north-1.amazonaws.com/devops_sec:latest

      - name: Push Docker Image to AWS ECR
        run: |
          docker push 476768693646.dkr.ecr.eu-north-1.amazonaws.com/devops_sec:latest
